source 'https://rubygems.org'

gem 'rails', '3.2.8'

## Gems used only for assets and not required
## in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # Cool assets generators/tools/libs
  gem 'jquery-rails'
  gem 'jquery-ui-rails'
  gem 'haml-rails'
  gem 'bootstrap-sass'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

# To use Jbuilder templates for JSON
gem 'jbuilder'

# Api Builder 
gem 'kaminari'
gem 'rocket_pants', git: 'git://github.com/elthariel/rocket_pants.git', branch: 'handle_mongoid_exceptions'

# MongoDB ODM
gem 'mongoid', "~> 3.0.0"
gem 'mongoid-tree', :require => 'mongoid/tree'

# Rails Admin
gem 'rails_admin'
gem 'devise'
gem 'cancan'

## Gems required only for development
## stations
group :development do
  # To use debugger
  if RUBY_VERSION =~ /1.9/ 
    gem 'ruby-debug19'
  else
    gem 'ruby-debug'
  end

  # for kill_erb script
  gem 'hpricot'
  gem 'ruby_parser'

  # for Mongo dump, restore, and hacking
  gem 'bson_ext'
  gem 'yajl-ruby'
end

# Used for seeds
gem "factory_girl_rails", "~> 4.0"
gem 'faker'

group :test, :development do
  gem "rspec-rails", "~> 2.0"
  gem 'mongoid-rspec'
  gem 'database_cleaner'
end
